# Generated by Django 5.0.14 on 2025-10-14 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reserved_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the reservation was made"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the reservation expires"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("converted_to_loan", "Converted to Loan"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        help_text="Current status of the reservation",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        help_text="Book being reserved",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made the reservation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "reservation",
                "verbose_name_plural": "reservations",
                "db_table": "reservations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrowed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the book was borrowed"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(help_text="When the book should be returned"),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, help_text="When the book was returned", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("returned", "Returned"),
                            ("overdue", "Overdue"),
                        ],
                        default="active",
                        help_text="Current status of the loan",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        help_text="Book being loaned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Current user who has the book",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reservation that was converted to this loan (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loans",
                        to="loans.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "loan",
                "verbose_name_plural": "loans",
                "db_table": "loans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transferred_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the transfer occurred"
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(
                        default=True, help_text="Whether the transfer was accepted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        help_text="User who is transferring the loan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_transfers_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        help_text="Loan being transferred",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="loans.loan",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        help_text="User who is receiving the loan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_transfers_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "loan transfer",
                "verbose_name_plural": "loan transfers",
                "db_table": "loan_transfers",
                "ordering": ["-transferred_at"],
                "indexes": [
                    models.Index(
                        fields=["loan"], name="loan_transf_loan_id_fa9858_idx"
                    ),
                    models.Index(
                        fields=["from_user"], name="loan_transf_from_us_716b38_idx"
                    ),
                    models.Index(
                        fields=["to_user"], name="loan_transf_to_user_a16e74_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["user", "status"], name="reservation_user_id_d4fda7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["book", "status"], name="reservation_book_id_61e67a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["expires_at"], name="reservation_expires_9dca17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["user", "status"], name="loans_user_id_efac20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["book", "status"], name="loans_book_id_6360b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["due_date"], name="loans_due_dat_3e4b70_idx"),
        ),
    ]
