# Generated by Django 5.0.14 on 2025-10-16 20:38

import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loantransfer",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "loan transfer",
                "verbose_name_plural": "loan transfers",
            },
        ),
        migrations.RemoveField(
            model_name="loantransfer",
            name="accepted",
        ),
        migrations.RemoveField(
            model_name="loantransfer",
            name="transferred_at",
        ),
        migrations.AddField(
            model_name="loantransfer",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the transfer request expires (24 hours)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loantransfer",
            name="responded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the transfer was accepted/rejected/cancelled",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loantransfer",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="pending",
                help_text="Current status of the transfer",
                max_length=20,
                protected=True,
            ),
        ),
        migrations.AddField(
            model_name="loantransfer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("active", "Active"),
                    ("returned", "Returned"),
                    ("overdue", "Overdue"),
                ],
                default="active",
                help_text="Current status of the loan",
                max_length=20,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="loantransfer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the transfer was created"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("converted_to_loan", "Converted to Loan"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                help_text="Current status of the reservation",
                max_length=20,
                protected=True,
            ),
        ),
        migrations.AddIndex(
            model_name="loantransfer",
            index=models.Index(fields=["status"], name="loan_transf_status_3fcd78_idx"),
        ),
        migrations.AddIndex(
            model_name="loantransfer",
            index=models.Index(
                fields=["expires_at"], name="loan_transf_expires_1b4cbb_idx"
            ),
        ),
    ]
