# Generated by Django 5.0.14 on 2025-10-14 21:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        help_text="ISBN-13 code for the book",
                        max_length=13,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the book", max_length=255),
                ),
                (
                    "author",
                    models.CharField(help_text="Author of the book", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the book"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Total quantity of books available in the library",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "available_quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Current quantity of books available for loan",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who added this book to the library",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "book",
                "verbose_name_plural": "books",
                "db_table": "books",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="books_title_7a737c_idx"),
                    models.Index(fields=["author"], name="books_author_1c43f5_idx"),
                    models.Index(fields=["isbn"], name="books_isbn_ce4a1a_idx"),
                ],
            },
        ),
    ]
